/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComicsComicIdRouteImport } from './routes/comics/$comicId'
import { Route as ChaptersChapterIdRouteImport } from './routes/chapters/$chapterId'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users/$userId'
import { Route as ApiRecommendationsChar123RecommendationIdChar125RouteImport } from './routes/api/recommendations/{-$recommendationId}'
import { Route as ApiPagesPageIdRouteImport } from './routes/api/pages/$pageId'
import { Route as ApiComicsChar123ComicIdChar125RouteImport } from './routes/api/comics/{-$comicId}'
import { Route as ApiChaptersChapterIdRouteImport } from './routes/api/chapters/$chapterId'
import { Route as ApiComicsComicIdChaptersRouteImport } from './routes/api/comics/$comicId.chapters'
import { Route as ApiChaptersChapterIdPagesRouteImport } from './routes/api/chapters/$chapterId.pages'
import { Route as ApiChaptersChapterIdCreditsRouteImport } from './routes/api/chapters/$chapterId.credits'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComicsComicIdRoute = ComicsComicIdRouteImport.update({
  id: '/comics/$comicId',
  path: '/comics/$comicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersChapterIdRoute = ChaptersChapterIdRouteImport.update({
  id: '/chapters/$chapterId',
  path: '/chapters/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/api/users/$userId',
  path: '/api/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecommendationsChar123RecommendationIdChar125Route =
  ApiRecommendationsChar123RecommendationIdChar125RouteImport.update({
    id: '/api/recommendations/{-$recommendationId}',
    path: '/api/recommendations/{-$recommendationId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPagesPageIdRoute = ApiPagesPageIdRouteImport.update({
  id: '/api/pages/$pageId',
  path: '/api/pages/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComicsChar123ComicIdChar125Route =
  ApiComicsChar123ComicIdChar125RouteImport.update({
    id: '/api/comics/{-$comicId}',
    path: '/api/comics/{-$comicId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChaptersChapterIdRoute = ApiChaptersChapterIdRouteImport.update({
  id: '/api/chapters/$chapterId',
  path: '/api/chapters/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComicsComicIdChaptersRoute =
  ApiComicsComicIdChaptersRouteImport.update({
    id: '/api/comics/$comicId/chapters',
    path: '/api/comics/$comicId/chapters',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChaptersChapterIdPagesRoute =
  ApiChaptersChapterIdPagesRouteImport.update({
    id: '/pages',
    path: '/pages',
    getParentRoute: () => ApiChaptersChapterIdRoute,
  } as any)
const ApiChaptersChapterIdCreditsRoute =
  ApiChaptersChapterIdCreditsRouteImport.update({
    id: '/credits',
    path: '/credits',
    getParentRoute: () => ApiChaptersChapterIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/comics/$comicId': typeof ComicsComicIdRoute
  '/api/chapters/$chapterId': typeof ApiChaptersChapterIdRouteWithChildren
  '/api/comics/{-$comicId}': typeof ApiComicsChar123ComicIdChar125Route
  '/api/pages/$pageId': typeof ApiPagesPageIdRoute
  '/api/recommendations/{-$recommendationId}': typeof ApiRecommendationsChar123RecommendationIdChar125Route
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/api/chapters/$chapterId/credits': typeof ApiChaptersChapterIdCreditsRoute
  '/api/chapters/$chapterId/pages': typeof ApiChaptersChapterIdPagesRoute
  '/api/comics/$comicId/chapters': typeof ApiComicsComicIdChaptersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/comics/$comicId': typeof ComicsComicIdRoute
  '/api/chapters/$chapterId': typeof ApiChaptersChapterIdRouteWithChildren
  '/api/comics/{-$comicId}': typeof ApiComicsChar123ComicIdChar125Route
  '/api/pages/$pageId': typeof ApiPagesPageIdRoute
  '/api/recommendations/{-$recommendationId}': typeof ApiRecommendationsChar123RecommendationIdChar125Route
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/api/chapters/$chapterId/credits': typeof ApiChaptersChapterIdCreditsRoute
  '/api/chapters/$chapterId/pages': typeof ApiChaptersChapterIdPagesRoute
  '/api/comics/$comicId/chapters': typeof ApiComicsComicIdChaptersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/comics/$comicId': typeof ComicsComicIdRoute
  '/api/chapters/$chapterId': typeof ApiChaptersChapterIdRouteWithChildren
  '/api/comics/{-$comicId}': typeof ApiComicsChar123ComicIdChar125Route
  '/api/pages/$pageId': typeof ApiPagesPageIdRoute
  '/api/recommendations/{-$recommendationId}': typeof ApiRecommendationsChar123RecommendationIdChar125Route
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/api/chapters/$chapterId/credits': typeof ApiChaptersChapterIdCreditsRoute
  '/api/chapters/$chapterId/pages': typeof ApiChaptersChapterIdPagesRoute
  '/api/comics/$comicId/chapters': typeof ApiComicsComicIdChaptersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/chapters/$chapterId'
    | '/comics/$comicId'
    | '/api/chapters/$chapterId'
    | '/api/comics/{-$comicId}'
    | '/api/pages/$pageId'
    | '/api/recommendations/{-$recommendationId}'
    | '/api/users/$userId'
    | '/api/chapters/$chapterId/credits'
    | '/api/chapters/$chapterId/pages'
    | '/api/comics/$comicId/chapters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/chapters/$chapterId'
    | '/comics/$comicId'
    | '/api/chapters/$chapterId'
    | '/api/comics/{-$comicId}'
    | '/api/pages/$pageId'
    | '/api/recommendations/{-$recommendationId}'
    | '/api/users/$userId'
    | '/api/chapters/$chapterId/credits'
    | '/api/chapters/$chapterId/pages'
    | '/api/comics/$comicId/chapters'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/chapters/$chapterId'
    | '/comics/$comicId'
    | '/api/chapters/$chapterId'
    | '/api/comics/{-$comicId}'
    | '/api/pages/$pageId'
    | '/api/recommendations/{-$recommendationId}'
    | '/api/users/$userId'
    | '/api/chapters/$chapterId/credits'
    | '/api/chapters/$chapterId/pages'
    | '/api/comics/$comicId/chapters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ChaptersChapterIdRoute: typeof ChaptersChapterIdRoute
  ComicsComicIdRoute: typeof ComicsComicIdRoute
  ApiChaptersChapterIdRoute: typeof ApiChaptersChapterIdRouteWithChildren
  ApiComicsChar123ComicIdChar125Route: typeof ApiComicsChar123ComicIdChar125Route
  ApiPagesPageIdRoute: typeof ApiPagesPageIdRoute
  ApiRecommendationsChar123RecommendationIdChar125Route: typeof ApiRecommendationsChar123RecommendationIdChar125Route
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
  ApiComicsComicIdChaptersRoute: typeof ApiComicsComicIdChaptersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comics/$comicId': {
      id: '/comics/$comicId'
      path: '/comics/$comicId'
      fullPath: '/comics/$comicId'
      preLoaderRoute: typeof ComicsComicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$chapterId': {
      id: '/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/chapters/$chapterId'
      preLoaderRoute: typeof ChaptersChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/api/users/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recommendations/{-$recommendationId}': {
      id: '/api/recommendations/{-$recommendationId}'
      path: '/api/recommendations/{-$recommendationId}'
      fullPath: '/api/recommendations/{-$recommendationId}'
      preLoaderRoute: typeof ApiRecommendationsChar123RecommendationIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pages/$pageId': {
      id: '/api/pages/$pageId'
      path: '/api/pages/$pageId'
      fullPath: '/api/pages/$pageId'
      preLoaderRoute: typeof ApiPagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comics/{-$comicId}': {
      id: '/api/comics/{-$comicId}'
      path: '/api/comics/{-$comicId}'
      fullPath: '/api/comics/{-$comicId}'
      preLoaderRoute: typeof ApiComicsChar123ComicIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chapters/$chapterId': {
      id: '/api/chapters/$chapterId'
      path: '/api/chapters/$chapterId'
      fullPath: '/api/chapters/$chapterId'
      preLoaderRoute: typeof ApiChaptersChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comics/$comicId/chapters': {
      id: '/api/comics/$comicId/chapters'
      path: '/api/comics/$comicId/chapters'
      fullPath: '/api/comics/$comicId/chapters'
      preLoaderRoute: typeof ApiComicsComicIdChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chapters/$chapterId/pages': {
      id: '/api/chapters/$chapterId/pages'
      path: '/pages'
      fullPath: '/api/chapters/$chapterId/pages'
      preLoaderRoute: typeof ApiChaptersChapterIdPagesRouteImport
      parentRoute: typeof ApiChaptersChapterIdRoute
    }
    '/api/chapters/$chapterId/credits': {
      id: '/api/chapters/$chapterId/credits'
      path: '/credits'
      fullPath: '/api/chapters/$chapterId/credits'
      preLoaderRoute: typeof ApiChaptersChapterIdCreditsRouteImport
      parentRoute: typeof ApiChaptersChapterIdRoute
    }
  }
}

interface ApiChaptersChapterIdRouteChildren {
  ApiChaptersChapterIdCreditsRoute: typeof ApiChaptersChapterIdCreditsRoute
  ApiChaptersChapterIdPagesRoute: typeof ApiChaptersChapterIdPagesRoute
}

const ApiChaptersChapterIdRouteChildren: ApiChaptersChapterIdRouteChildren = {
  ApiChaptersChapterIdCreditsRoute: ApiChaptersChapterIdCreditsRoute,
  ApiChaptersChapterIdPagesRoute: ApiChaptersChapterIdPagesRoute,
}

const ApiChaptersChapterIdRouteWithChildren =
  ApiChaptersChapterIdRoute._addFileChildren(ApiChaptersChapterIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ChaptersChapterIdRoute: ChaptersChapterIdRoute,
  ComicsComicIdRoute: ComicsComicIdRoute,
  ApiChaptersChapterIdRoute: ApiChaptersChapterIdRouteWithChildren,
  ApiComicsChar123ComicIdChar125Route: ApiComicsChar123ComicIdChar125Route,
  ApiPagesPageIdRoute: ApiPagesPageIdRoute,
  ApiRecommendationsChar123RecommendationIdChar125Route:
    ApiRecommendationsChar123RecommendationIdChar125Route,
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
  ApiComicsComicIdChaptersRoute: ApiComicsComicIdChaptersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
